export const pricingTiers = [
  {
    title: "Free",
    monthlyPrice: 0,
    buttonText: "Get started for free",
    description: "For small teams",
    popular: false,
    inverse: false,
    features: [
      "Up to 5 project members",
      "Unlimited tasks and projects",
      "2GB storage",
      "Integrations",
      "Basic support",
    ],
    notIncluded: ["expert support", "Dedicated account manager", "Custom fields", "Advanced analytics", "API access"],
  },
  {
    title: "Pro",
    monthlyPrice: 9,
    buttonText: "Sign up now",
    description: "For growing teams",
    popular: true,
    inverse: true,
    features: [
      "Up to 50 project members",
      "Unlimited tasks and projects",
      "50GB storage",
      "Integrations",
      "Expert support",
      "Custom fields",
      "Advanced analytics",
      "Advanced analytics",
      "Advanced analytics",
      "Advanced analytics",
      "Advanced analytics",
      "Advanced analytics",

    ],
    notIncluded: ["Dedicated account manager", "API access", "Advanced security features"],
  },
  {
    title: "Business",
    monthlyPrice: 19,
    buttonText: "Sign up now",
    description: "For large teams",
    popular: false,
    inverse: false,
    features: [
      "Up to 5 project members",
      "Unlimited tasks and projects",
      "200GB storage",
      "Integrations",
      "Dedicated account manager",
      "Custom fields",
      "Advanced analytics",
      "Export capabilities",
      "API access",
      "Advanced security features",
    ],
    notIncluded: [],
  },
  
];
